"""
Django settings for rakubaruproj project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=2b1rvvgca*^i6x0a1&qak-n78jmak(29z*^&a2n)!$bjj)5xc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['www.rakubaru-posting.com']

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.smtp2go.com'
EMAIL_PORT = 2525
EMAIL_HOST_USER = 'nac-om.com'
EMAIL_HOST_PASSWORD = 'Rakubaru!@#$%^&*'

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rakubaru.apps.RakubaruConfig',
    'fcm_django',
    'background_task',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rakubaruproj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]

WSGI_APPLICATION = 'rakubaruproj.wsgi.application'

DATA_UPLOAD_MAX_MEMORY_SIZE = 115242880


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',

        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
         },

        'NAME': 'HirotakaYamamoto$rakubaru',
        'USER': 'HirotakaYamamoto',
        'PASSWORD': '!@#$%qwe12345',
        'HOST': 'HirotakaYamamoto.mysql.pythonanywhere-services.com'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# default static files settings for PythonAnywhere.
# see https://help.pythonanywhere.com/pages/DjangoStaticFiles for more info
MEDIA_ROOT = '/home/HirotakaYamamoto/rakubaruproj/media'
MEDIA_URL = '/media/'
STATIC_ROOT = '/home/HirotakaYamamoto/rakubaruproj/rakubaru/static'
STATIC_URL = '/static/'

URL = 'https://www.rakubaru-posting.com'

RAKUBARU_ADMIN_EMAIL = 'rakubaru2020@gmail.com'


STRIPE_LIVE_SECRET_KEY = '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'
STRIPE_TEST_SECRET_KEY = 'sk_test_51Hr8pdECq8YGopGg3WmI3JLKqlDju1tdT3f4vAL8y5vmOMXMjz9SBrsr6gZVWsfFUBAiwVXf80SU1jqZaDlO8Pe700Utvh0BGU'

#   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

#   pk_live_51Hr8pdECq8YGopGg8KDcu5rS2vpS5u5K5d2eU9KL0OSlLGy5Nx2h5UIi2hRXlw2PCy8PYhyU1iT93vBXX02nq1yT00Q1UDxDUs

#   pk_test_51Hr8pdECq8YGopGgUx1FE1iUfberafsAxdiVFCoHBy7XflTnxYm28Gd2F8QrUBkVKtS4TmZ25twwL8ky2py6plMR00kwvysIGH





















